export const FETCH_DATA_USER = "FETCH_DATA_USER";
export const FETCH_DATA_ADMIN = "FETCH_DATA_ADMIN";

export const FETCH_DATA_USER_SUCCESS = "FETCH_DATA_USER_SUCCESS";
export const FETCH_DATA_USER_ERROR = "FETCH_DATA_USER_ERROR";
export const FETCH_DATA_ADMIN_SUCCESS = "FETCH_DATA_ADMIN_SUCCESS";
export const FETCH_DATA_ADMIN_ERROR = "FETCH_DATA_ADMIN_ERROR";

export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const SET_STATE_ADMIN_PANEL = "SET_STATE_ADMIN_PANEL";
export const RELOAD_STATE_ADMIN_PANEL = "RELOAD_STATE_ADMIN_PANEL";

export const SET_CURRENT_SHOW_ADMIN_PANEL = "SET_CURRENT_SHOW_ADMIN_PANEL";
export const RELOAD_CURRENT_SHOW_ADMIN_PANEL = "RELOAD_CURRENT_SHOW_ADMIN_PANEL";
